### ISSUE TITLE
add dummy.json file to store the students name

### ISSUE THREAD

**Issue by chandantiwari1** [chandantiwari1/students-portal#7]
this file will store the names of the students

**Comment by Saurabh-kumar44** [comment]
Assign this to me

**Comment by RuthChisom** [comment]
Hello, I'd love to work on this. Kindly assign this to me. Thanks.

**Comment by sharmapranay38** [comment]
assign it to me

**Comment by chandantiwari1** [comment]
@shivvamm assigned to you
